spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mvc:
    # /static/ 으로 시작하는 요청에 대해 정적 파일 서빙
    static-path-pattern: /static/**
  web:
    resources:
      # 정적 파일 탐색 장소
      static-locations: file:media/,classpath:/static


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${google_mail_username}
    password: ${google_mail_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google_id}
            client-secret: ${google_secret}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
          naver:
            client-id: ${naver_id}
            client-secret: ${naver_secret}
            client-name: Naver
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
          kakao:
            client-id: ${kakao_id}
            client-secret: ${kakao_secret}
            client-name: Kakao
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
springdoc:
  swagger-ui:
    path: /swagger

jwt:
  secret: ${jwt_secret}