spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mysql://localhost:3307/team8
    username: {db_username}
    password: {db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
  batch:
    jdbc:
      initialize-schema: ALWAYS
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        globally_quoted_identifiers: true
        #        globally_quoted_identifiers_skip_column_definitions: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema-mysql.sql
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${google_mail_username}
    password: ${google_mail_password}
  rabbitmq:
    host: ${rabbit_host}
    username: ${rabbit_user}
    password: ${rabbit_password}
logging:
  level:
    org.hibernate.SQL: debug
jwt:
  secret: ${jwt_secret}
server:
  port: 8081