INSERT INTO users (created_date, modified_date, email, username, password, phone, provider, role, point, one_line_introduction, profileurl) VALUES (NOW(), NOW(), 'gyeongnam@gmail.com', 'gyeongnam', '$2a$10$sBLW3YgStvQtnJ..g0HtPOVuEO.wK5AmQ5lJeUQ85Nzmum1n8ZJyK', '010-1234-5678', 'LOCAL', 'ROLE_USER', 10000, '코드는 나의 언어, 미래를 만들어가는 소프트웨어 엔지니어', '/static/USER_PROFILE/gyeongnam.jpg');
INSERT INTO users (created_date, modified_date, email, username, password, phone, provider, role, point, one_line_introduction, profileurl) VALUES (NOW(), NOW(), 'gangmin@gmail.com', 'gangmin', '$2a$10$A6iy8d7XnwDyY/JRD3Fiw.zg2pJmp5RjkMnj7I.5w/ISJ7TuQeiSe', '010-1234-5678', 'LOCAL', 'ROLE_USER', 11000, '프로그래밍의 매력에 빠져, 끝없는 코드 여행을 떠나는 중', '/static/USER_PROFILE/gangmin.jpg');
INSERT INTO users (created_date, modified_date, email, username, password, phone, provider, role, point, one_line_introduction, profileurl) VALUES (NOW(), NOW(), 'sukeun@gmail.com', 'sukeun', '$2a$10$pkkXP1aC5yTTbVKQifexKuUSfOB6J5kGpF4GV4KHAVPqkSAk5VUCO', '010-1234-5678', 'LOCAL', 'ROLE_USER', 12000, '데이터 마술사로, 알고리즘에 깊은 관심을 가진 데이터 분석가', '/static/USER_PROFILE/sukeun.jpeg');
INSERT INTO users (created_date, modified_date, email, username, password, phone, provider, role, point, one_line_introduction, profileurl) VALUES (NOW(), NOW(), 'jaehwan@gmail.com', 'jaehwan', '$2a$10$mIFRje7wzppchnFVCpseK.FSKjLDFHv3A3Rr66NaFZf4o6z.UilDm', '010-1234-5678', 'LOCAL', 'ROLE_USER', 13000, '게임 개발의 열정적인 마니아, 가상 세계 창조자', '/static/USER_PROFILE/jaehwan.jpeg');
INSERT INTO users (created_date, modified_date, email, username, password, phone, provider, role, point, one_line_introduction, profileurl) VALUES (NOW(), NOW(), 'gyuhee@gmail.com', 'gyuhee', '$2a$10$HZVBZXXkMbeN.tUwNXyb4Oo2Zwf6YvBOxQqQYL0wlaqHJ6r13sErm', '010-1234-5678', 'LOCAL', 'ROLE_USER', 14000, '웹 개발자로, 사용자 경험을 개선하는 데 헌신', '/static/USER_PROFILE/gyuhee.jpeg');
INSERT INTO users (created_date, modified_date, email, username, password, phone, provider, role, point, one_line_introduction, profileurl) VALUES (NOW(), NOW(), 'kitae@gmail.com', 'kitae', '$2a$10$ckGkXQ0e.NL4ExD.RjWvPuvC43cH1bopUz5EqasjB3KUZXByvwLj.', '010-1234-5678', 'LOCAL', 'ROLE_USER', 15000, 'AI와 머신러닝에 빠져있는 미래 지향적인 데이터 과학자', '/static/USER_PROFILE/user1.jpg');
INSERT INTO users (created_date, modified_date, email, username, password, phone, provider, role, point, one_line_introduction, profileurl) VALUES (NOW(), NOW(), 'kimberley@gmail.com', 'kimberley', '$2a$10$3ox6l7keiMC.WfTt4OF6LOR3B72rNndufpP6vtZmmfsSf6swy69Xm', '010-1234-5678', 'LOCAL', 'ROLE_USER', 16000, '보안 전문가로, 디지털 세계를 안전하게 유지하는 임무 수행 중', '/static/USER_PROFILE/user2.jpg');
INSERT INTO users (created_date, modified_date, email, username, password, phone, provider, role, point, one_line_introduction, profileurl) VALUES (NOW(), NOW(), 'kimura@gmail.com', 'kimura', '$2a$10$f3w6d6BDyU.CLlxv5iZQT.wtmgPF5M./3zoUDDs9mdLfC9ZBwlj/y', '010-1234-5678', 'LOCAL', 'ROLE_USER', 17000, '오픈 소스 기여자로, 커뮤니티와 함께 성장하는 프로그래머', '/static/USER_PROFILE/user3.jpg');
INSERT INTO users (created_date, modified_date, email, username, password, phone, provider, role, point, one_line_introduction, profileurl) VALUES (NOW(), NOW(), 'kimgyeongnam@gmail.com', 'kimgyeongnam', '$2a$10$sbfsWjySSsLrtBCCE2hOxuc3yxlmWTM9P8dsLTvYocYsHH6XDLfYm', '010-1234-5678', 'LOCAL', 'ROLE_USER', 18000, '모바일 앱 개발자로, 스마트폰에서의 혁신을 추구', '/static/USER_PROFILE/user4.jpg');
INSERT INTO users (created_date, modified_date, email, username, password, phone, provider, role, point, one_line_introduction, profileurl) VALUES (NOW(), NOW(), 'kimkardashian@gmail.com', 'kimkardashian', '$2a$10$OROngbiriYyWWnyZYbVRs.rwBX/lzZTasNP5MIFL0IGOc24PIbtZi', '010-1234-5678', 'LOCAL', 'ROLE_USER', 19000, '블록체인 열렬한 추종자로, 탈중앙화된 미래를 향해 나아가는 중', '/static/USER_PROFILE/user5.jpg');
INSERT INTO users (created_date, modified_date, email, username, password, phone, provider, role, point, one_line_introduction, profileurl) VALUES (NOW(), NOW(), 'kitaek@gmail.com', 'kitaek', '$2a$10$i/YvoDMqsrBYn5sz0prfIeDbz2Y9IeB26gHOQNZUdL7swpd2KWcm.', '010-1234-5678', 'LOCAL', 'ROLE_USER', 20000, '개발만이 살 길이다', '/static/USER_PROFILE/user6.jpg');
INSERT INTO users (created_date, modified_date, email, username, password, phone, provider, role, point, one_line_introduction, profileurl) VALUES (NOW(), NOW(), 'kimora@gmail.com', 'kimora', '$2a$10$ev0CZouZFPF/a0.i7c6s2.PRZw/l/BCkY9vjuWlvJVvENySlnGQ3e', '010-1234-5678', 'LOCAL', 'ROLE_USER', 21000, '제발 취업 시켜 주세요', '/static/USER_PROFILE/user7.jpg');

INSERT INTO categories (name) VALUES ('프론트엔드');
INSERT INTO categories (name) VALUES ('백엔드');
INSERT INTO categories (name) VALUES ('데이터베이스');
INSERT INTO categories (name) VALUES ('자료구조');
INSERT INTO categories (name) VALUES ('네트워크');
INSERT INTO categories (name) VALUES ('서버 / 클라우드');
INSERT INTO categories (name) VALUES ('게임');
INSERT INTO categories (name) VALUES ('소프트웨어');

INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (3,1,'React Hooks를 활용한 간단한 To-Do 앱 튜토리얼','오늘은 React Hooks를 사용하여 간단한 To-Do 애플리케이션을 만드는 방법을 공유합니다. 코드와 설명을 확인해주세요!','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (1,2,'Python으로 데이터 시각화하기','Matplotlib과 Seaborn을 사용하여 데이터 시각화를 하는 방법에 대한 팁과 예제 코드를 공유합니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (3,1,'JavaScript의 최신 기능들을 살펴보기','ECMAScript 2023의 새로운 기능과 JavaScript의 최신 동향을 토론하고 공유하는 스레드입니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (3,1,'Front-end 개발자들을 위한 CSS 그리드 시스템 안내','CSS 그리드 시스템을 활용하여 웹 디자인을 효과적으로 개발하는 방법에 대한 가이드입니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (2,2,'파이썬을 사용한 머신러닝 프로젝트 공유','파이썬과 Scikit-learn을 활용하여 간단한 머신러닝 프로젝트를 구현하고 결과를 공유합니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (4,8,'최신 웹 개발 도구와 라이브러리 소개','웹 개발자를 위한 최신 도구와 라이브러리를 소개하고 어떻게 활용하는지에 대한 토론입니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (5,5,'Git과 GitHub를 활용한 협업 방법','Git을 효과적으로 사용하고 GitHub를 통한 협업 프로세스를 공유하는 글입니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (1,6,'AWS 클라우드 서비스의 기초','Amazon Web Services (AWS)의 기초를 이해하고 클라우드 서비스를 활용하는 방법에 대한 자료입니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (2,6,'Docker 컨테이너화와 배포 전략','Docker를 사용하여 어플리케이션을 컨테이너화하고 배포하는 전략과 관련된 정보를 공유합니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (4,8,'개발자 커리어 관리 팁','개발자 커리어를 관리하고 성장하기 위한 조언과 경험을 나누는 글입니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (3,1,'Vue.js로 시작하는 프론트엔드 개발','Vue.js를 활용하여 싱글 페이지 애플리케이션을 개발하는 방법과 Vue.js의 주요 기능을 소개하는 글입니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (5,2,'REST API 디자인 원칙과 예시','RESTful API 디자인의 기본 원칙과 실제 예시를 통해 어떻게 효과적인 API를 설계하는지 알아봅니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (1,8,'프론트엔드 vs 백엔드 개발 - 어떤 경로를 선택할까요?','프론트엔드와 백엔드 개발 경로에 대한 비교 및 각각의 역할과 기술 요구사항에 대한 토론입니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (2,3,'데이터베이스 최적화 전략','데이터베이스 쿼리 최적화, 인덱싱, 캐싱 등 데이터베이스 성능 향상을 위한 전략과 팁을 다룹니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (3,6,'AWS Lambda와 서버리스 아키텍처 소개','서버리스 아키텍처의 기초를 이해하고 AWS Lambda를 사용하여 간단한 서버리스 애플리케이션을 만드는 방법을 공유합니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (4,8,'프로그래밍 언어 선택 가이드','어떤 프로그래밍 언어를 학습하고 사용해야 하는지에 대한 판단 기준과 각 언어의 특징에 대한 정보를 제공합니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (5,8,'커뮤니티 참여를 통한 개발자 네트워킹','개발자 커뮤니티와 오픈 소스 프로젝트에 참여하면서 네트워킹 기회를 확장하는 방법을 공유합니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (1,5,'웹 보안의 중요성과 보안 취약점 예방 전략','웹 애플리케이션 보안에 대한 이해와 주요 보안 취약점을 예방하기 위한 전략을 다루는 글입니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (2,8,'애자일 소프트웨어 개발 방법론 소개','애자일 소프트웨어 개발 방법론의 기본 개념과 원칙을 소개하고 프로젝트에 적용하는 방법을 논의합니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (3,8,'커리어 전환 - 개발자에서 데브옵스 엔지니어로','개발자에서 데브옵스 엔지니어로의 커리어 전환 경험과 조언을 공유하는 글입니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (4,3,'GraphQL을 사용한 API 개발 팁','GraphQL을 활용하여 유연하고 효율적인 API를 개발하는 방법과 예시 코드를 공유합니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (5,5,'CI/CD 파이프라인 구축하기','지속적 통합 (CI) 및 지속적 배포 (CD) 파이프라인을 구축하고 자동화하는 방법에 대한 안내입니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (1,4,'컴퓨터 과학 기초 다지기','자료 구조, 알고리즘, 복잡도 분석 등 컴퓨터 과학의 기초 개념을 되짚어보는 자료입니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (2,6,'웹 개발에서의 성능 최적화 전략','웹 페이지 로딩 시간을 단축하고 성능을 향상시키기 위한 웹 개발 성능 최적화 팁과 도구 소개입니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (3,8,'오픈 소스 개발에 기여하는 방법','오픈 소스 프로젝트에 참여하고 기여하는 방법과 첫 번째 기여를 시작하는 가이드입니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (3,1,'JavaScript 프레임워크 비교: React vs. Angular vs. Vue','React, Angular, Vue.js의 특징과 장단점을 비교하여 어떤 프레임워크를 선택해야 하는지 논의합니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (4,8,'데이터 사이언스와 머신러닝 실전 프로젝트','머신러닝 모델을 사용하여 실제 데이터를 분석하고 예측하는 데이터 사이언스 프로젝트에 대한 경험 공유입니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (5,8,'코딩 인터뷰를 위한 팁과 자료 구조 문제 해결 전략','코딩 인터뷰에서 성공하기 위한 팁과 자료 구조 및 알고리즘 문제 해결 전략을 공유합니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (1,5,'클라우드 보안 Best Practices','클라우드 환경에서의 보안을 강화하기 위한 최고의 실천 방법과 도구를 알아봅니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (2,8,'개발자 커뮤니티에서의 활동과 혜택','개발자 커뮤니티에 참여하여 지식 공유, 네트워킹, 그리고 새로운 기회를 찾는 방법과 이점에 대한 이야기입니다.','PUBLIC','NORMAL');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (4,1,'React에서 상태 관리를 위해 Redux 대신 Context API를 사용하는 것은 어떤가요?','저는 최근에 React 프로젝트를 시작했는데, Redux 대신에 Context API를 사용해보려고 합니다. 어떤 경우에 Redux보다 Context API를 사용하는 것이 좋을까요? 그리고 이러한 전환 과정에서 유의할 점이 있을까요?','PUBLIC','QUESTION');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (5,2,'Python vs. JavaScript: 어떤 언어를 웹 개발에 사용해야 할까요?','웹 개발을 시작하려고 하는데, Python과 JavaScript 중 어떤 언어를 선택해야 할지 고민 중입니다. 각 언어의 장단점과 어떤 프로젝트에 어떤 언어가 더 적합한지에 대한 조언을 부탁드립니다.','PUBLIC','QUESTION');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (1,6,'Git에서 충돌 해결을 위한 최상의 방법은 무엇인가요?','Git을 사용하면서 종종 충돌 문제를 마주하게 됩니다. 충돌을 해결하는 데 가장 효과적인 방법은 무엇일까요? 어떤 도구나 전략을 사용하시나요?','PUBLIC','QUESTION');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (2,1,'프론트엔드 개발자로 취업하려면 어떤 기술 스택을 익혀야 할까요?','프론트엔드 개발자로의 커리어를 시작하려고 합니다. 어떤 기술 스택을 공부하고 익혀야 취업 기회를 높일 수 있을까요? 어떤 프로젝트를 통해 경험을 쌓는 것이 좋을까요?','PUBLIC','QUESTION');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (3,8,'안드로이드 vs. iOS 개발: 어떤 플랫폼이 더 유망한가요?','안드로이드와 iOS 개발 중 어느 쪽이 미래에 더 유망하다고 생각하십니까? 어떤 플랫폼을 공부하고 마스터하는 데 가치가 있을까요?','PUBLIC','QUESTION');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (4,6,'RESTful API와 GraphQL 중 어떤 것을 선택해야 할까요?','서버 개발 중에 RESTful API와 GraphQL 중 어떤 것을 선택해야 하는지에 대한 고민이 있습니다. 각각의 장단점과 어떤 상황에서 어떤 것을 사용해야 하는지에 대한 조언을 부탁드립니다.','PUBLIC','QUESTION');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (5,6,'Docker와 Kubernetes: 컨테이너 오케스트레이션에 대한 이해가 필요합니다.','컨테이너 관리와 배포를 위해 Docker와 Kubernetes를 사용하려고 합니다. 이 두 기술에 대한 기본 개념과 시작하는 데 도움이 되는 자료나 자원을 추천해 주실 수 있을까요?','PUBLIC','QUESTION');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (1,8,'테스트 주도 개발(TDD)의 장점과 어떻게 시작해야 할까요?','TDD에 대해 들어봤는데, 어떤 장점이 있는지 이해하고 싶습니다. 또한 TDD를 실제 프로젝트에 적용하기 위해 어떻게 시작해야 하는지에 대한 가이드를 부탁드립니다.','PUBLIC','QUESTION');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (2,8,'보안 취약점을 예방하기 위한 웹 애플리케이션 보안 팁이 필요합니다.','웹 애플리케이션을 개발하면서 보안 취약점을 최소화하고자 합니다. XSS, CSRF 등의 보안 문제를 예방하는 팁과 관련 자료를 추천해 주실 수 있을까요?','PUBLIC','QUESTION');
INSERT INTO feeds (user_id, category_id, title, content, scope, type) VALUES (3,8,'커리어 전환: 개발자에서 데브옵스 엔지니어로의 스스로의 길을 만들기','개발자에서 데브옵스 엔지니어로의 커리어 전환이 필요하다고 생각합니다. 필요한 스킬셋과 리소스를 어떻게 구축해야 할지에 대한 조언을 부탁드립니다.','PUBLIC','QUESTION');

INSERT INTO images (feed_id, imageurl) VALUES (1,'/static/FEED/1-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (1,'/static/FEED/1-2.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (1,'/static/FEED/1-3.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (1,'/static/FEED/1-4.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (1,'/static/FEED/1-5.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (2,'/static/FEED/2-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (2,'/static/FEED/2-2.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (3,'/static/FEED/3-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (3,'/static/FEED/3-2.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (3,'/static/FEED/3-3.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (4,'/static/FEED/4-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (4,'/static/FEED/4-2.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (5,'/static/FEED/5-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (5,'/static/FEED/5-2.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (5,'/static/FEED/5-3.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (6,'/static/FEED/6-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (7,'/static/FEED/7-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (8,'/static/FEED/8-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (9,'/static/FEED/9-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (9,'/static/FEED/9-2.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (9,'/static/FEED/9-3.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (10,'/static/FEED/10-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (11,'/static/FEED/11-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (11,'/static/FEED/11-2.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (12,'/static/FEED/12-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (13,'/static/FEED/13-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (14,'/static/FEED/14-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (15,'/static/FEED/15-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (15,'/static/FEED/15-2.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (16,'/static/FEED/16-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (17,'/static/FEED/17-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (18,'/static/FEED/18-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (19,'/static/FEED/19-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (20,'/static/FEED/20-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (20,'/static/FEED/20-2.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (21,'/static/FEED/21-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (22,'/static/FEED/22-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (23,'/static/FEED/23-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (24,'/static/FEED/24-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (25,'/static/FEED/25-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (26,'/static/FEED/26-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (27,'/static/FEED/27-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (28,'/static/FEED/28-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (29,'/static/FEED/29-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (30,'/static/FEED/30-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (31,'/static/FEED/31-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (32,'/static/FEED/32-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (33,'/static/FEED/33-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (34,'/static/FEED/34-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (35,'/static/FEED/35-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (36,'/static/FEED/36-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (37,'/static/FEED/37-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (38,'/static/FEED/38-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (39,'/static/FEED/39-1.jpg');
INSERT INTO images (feed_id, imageurl) VALUES (40,'/static/FEED/40-1.jpg');

INSERT INTO follows (who_follow, follow_who) VALUES (12, 1);
INSERT INTO follows (who_follow, follow_who) VALUES (12, 2);
INSERT INTO follows (who_follow, follow_who) VALUES (12, 3);
INSERT INTO follows (who_follow, follow_who) VALUES (12, 4);
INSERT INTO follows (who_follow, follow_who) VALUES (12, 5);
INSERT INTO follows (who_follow, follow_who) VALUES (12, 6);
INSERT INTO follows (who_follow, follow_who) VALUES (12, 7);
INSERT INTO follows (who_follow, follow_who) VALUES (12, 8);
INSERT INTO follows (who_follow, follow_who) VALUES (12, 9);
INSERT INTO follows (who_follow, follow_who) VALUES (12, 10);
INSERT INTO follows (who_follow, follow_who) VALUES (12, 11);
INSERT INTO follows (who_follow, follow_who) VALUES (11, 1);
INSERT INTO follows (who_follow, follow_who) VALUES (11, 2);
INSERT INTO follows (who_follow, follow_who) VALUES (11, 3);
INSERT INTO follows (who_follow, follow_who) VALUES (11, 4);
INSERT INTO follows (who_follow, follow_who) VALUES (11, 5);
INSERT INTO follows (who_follow, follow_who) VALUES (11, 6);
INSERT INTO follows (who_follow, follow_who) VALUES (11, 7);
INSERT INTO follows (who_follow, follow_who) VALUES (11, 8);
INSERT INTO follows (who_follow, follow_who) VALUES (11, 9);
INSERT INTO follows (who_follow, follow_who) VALUES (11, 10);
INSERT INTO follows (who_follow, follow_who) VALUES (10, 1);
INSERT INTO follows (who_follow, follow_who) VALUES (10, 2);
INSERT INTO follows (who_follow, follow_who) VALUES (10, 3);
INSERT INTO follows (who_follow, follow_who) VALUES (10, 4);
INSERT INTO follows (who_follow, follow_who) VALUES (10, 5);
INSERT INTO follows (who_follow, follow_who) VALUES (10, 6);
INSERT INTO follows (who_follow, follow_who) VALUES (10, 7);
INSERT INTO follows (who_follow, follow_who) VALUES (10, 8);
INSERT INTO follows (who_follow, follow_who) VALUES (10, 9);
INSERT INTO follows (who_follow, follow_who) VALUES (9, 1);
INSERT INTO follows (who_follow, follow_who) VALUES (9, 2);
INSERT INTO follows (who_follow, follow_who) VALUES (9, 3);
INSERT INTO follows (who_follow, follow_who) VALUES (9, 4);
INSERT INTO follows (who_follow, follow_who) VALUES (9, 5);
INSERT INTO follows (who_follow, follow_who) VALUES (9, 6);
INSERT INTO follows (who_follow, follow_who) VALUES (9, 7);
INSERT INTO follows (who_follow, follow_who) VALUES (9, 8);
INSERT INTO follows (who_follow, follow_who) VALUES (8, 1);
INSERT INTO follows (who_follow, follow_who) VALUES (8, 2);
INSERT INTO follows (who_follow, follow_who) VALUES (8, 3);
INSERT INTO follows (who_follow, follow_who) VALUES (8, 4);
INSERT INTO follows (who_follow, follow_who) VALUES (8, 5);
INSERT INTO follows (who_follow, follow_who) VALUES (8, 6);
INSERT INTO follows (who_follow, follow_who) VALUES (8, 7);
INSERT INTO follows (who_follow, follow_who) VALUES (7, 1);
INSERT INTO follows (who_follow, follow_who) VALUES (7, 2);
INSERT INTO follows (who_follow, follow_who) VALUES (7, 3);
INSERT INTO follows (who_follow, follow_who) VALUES (7, 4);
INSERT INTO follows (who_follow, follow_who) VALUES (7, 5);
INSERT INTO follows (who_follow, follow_who) VALUES (7, 6);
INSERT INTO follows (who_follow, follow_who) VALUES (6, 1);
INSERT INTO follows (who_follow, follow_who) VALUES (6, 2);
INSERT INTO follows (who_follow, follow_who) VALUES (6, 3);
INSERT INTO follows (who_follow, follow_who) VALUES (6, 4);
INSERT INTO follows (who_follow, follow_who) VALUES (6, 5);
INSERT INTO follows (who_follow, follow_who) VALUES (5, 1);
INSERT INTO follows (who_follow, follow_who) VALUES (5, 2);
INSERT INTO follows (who_follow, follow_who) VALUES (5, 3);
INSERT INTO follows (who_follow, follow_who) VALUES (5, 4);
INSERT INTO follows (who_follow, follow_who) VALUES (4, 1);
INSERT INTO follows (who_follow, follow_who) VALUES (4, 2);
INSERT INTO follows (who_follow, follow_who) VALUES (4, 3);
INSERT INTO follows (who_follow, follow_who) VALUES (3, 1);
INSERT INTO follows (who_follow, follow_who) VALUES (3, 2);
INSERT INTO follows (who_follow, follow_who) VALUES (2, 1);

INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 1, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 2, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 3, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 4, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 5, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 6, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 7, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 8, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 9, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 10, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 11, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 12, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 13, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 14, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 15, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 16, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 17, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 18, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 19, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 20, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 21, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 22, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 23, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 24, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 25, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 26, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 27, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 28, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 29, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 30, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 31, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 32, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 33, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 34, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 35, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 36, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 37, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 38, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 39, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(1, 40, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 1, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 2, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 3, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 4, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 5, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 6, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 7, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 8, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 9, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 10, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 11, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 12, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 13, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 14, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 15, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 16, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 17, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 18, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 19, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 20, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 21, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 22, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 23, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 24, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 25, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 26, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 27, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 28, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 29, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 30, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 31, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 32, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 33, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 34, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 35, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 36, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 37, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 38, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(2, 39, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 1, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 2, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 3, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 4, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 5, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 6, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 7, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 8, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 9, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 10, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 11, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 12, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 13, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 14, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 15, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 16, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 17, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 18, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 19, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 20, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 21, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 22, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 23, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 24, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 25, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 26, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 27, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 28, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 29, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 30, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 31, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 32, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 33, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 34, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 35, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 36, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 37, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(3, 38, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 1, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 2, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 3, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 4, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 5, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 6, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 7, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 8, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 9, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 10, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 11, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 12, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 13, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 14, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 15, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 16, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 17, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 18, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 19, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 20, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 21, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 22, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 23, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 24, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 25, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 26, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 27, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 28, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 29, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 30, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 31, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 32, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 33, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 34, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 35, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 36, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(4, 37, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 1, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 2, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 3, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 4, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 5, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 6, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 7, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 8, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 9, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 10, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 11, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 12, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 13, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 14, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 15, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 16, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 17, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 18, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 19, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 20, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 21, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 22, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 23, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 24, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 25, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 26, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 27, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 28, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 29, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 30, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 31, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 32, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 33, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 34, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 35, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(5, 36, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 1, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 2, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 3, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 4, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 5, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 6, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 7, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 8, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 9, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 10, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 11, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 12, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 13, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 14, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 15, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 16, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 17, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 18, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 19, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 20, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 21, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 22, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 23, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 24, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 25, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 26, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 27, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 28, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 29, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 30, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 31, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 32, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 33, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 34, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(6, 35, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 1, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 2, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 3, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 4, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 5, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 6, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 7, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 8, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 9, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 10, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 11, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 12, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 13, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 14, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 15, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 16, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 17, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 18, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 19, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 20, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 21, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 22, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 23, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 24, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 25, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 26, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 27, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 28, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 29, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 30, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 31, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 32, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 33, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(7, 34, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 1, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 2, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 3, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 4, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 5, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 6, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 7, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 8, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 9, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 10, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 11, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 12, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 13, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 14, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 15, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 16, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 17, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 18, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 19, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 20, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 21, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 22, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 23, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 24, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 25, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 26, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 27, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 28, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 29, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 30, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 31, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 32, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(8, 33, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 1, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 2, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 3, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 4, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 5, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 6, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 7, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 8, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 9, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 10, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 11, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 12, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 13, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 14, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 15, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 16, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 17, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 18, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 19, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 20, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 21, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 22, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 23, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 24, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 25, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 26, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 27, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 28, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 29, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 30, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 31, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(9, 32, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 1, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 2, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 3, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 4, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 5, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 6, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 7, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 8, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 9, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 10, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 11, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 12, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 13, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 14, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 15, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 16, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 17, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 18, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 19, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 20, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 21, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 22, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 23, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 24, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 25, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 26, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 27, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 28, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 29, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 30, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(10, 31, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 1, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 2, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 3, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 4, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 5, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 6, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 7, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 8, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 9, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 10, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 11, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 12, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 13, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 14, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 15, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 16, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 17, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 18, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 19, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 20, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 21, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 22, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 23, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 24, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 25, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 26, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 27, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 28, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 29, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(11, 30, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 1, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 2, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 3, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 4, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 5, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 6, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 7, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 8, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 9, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 10, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 11, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 12, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 13, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 14, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 15, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 16, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 17, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 18, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 19, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 20, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 21, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 22, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 23, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 24, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 25, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 26, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 27, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 28, 'N');
INSERT INTO likes (user_id, feed_id, cancel_yn) VALUES(12, 29, 'N');

INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (1, 4, '이 튜토리얼 정말 유용하네요! Hooks를 처음 배우는데 도움이 많이 되었습니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (1, 5, 'To-Do 앱 만들기는 항상 좋은 연습입니다. 간단하면서도 React Hooks를 잘 활용한 예제네요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (1, 6, '좋은 설명과 함께 더미 댓글도 작성해보겠습니다. 이 튜토리얼을 따라하면서 많은 것을 배웠어요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (2, 7, '데이터 시각화는 데이터 분석의 중요한 부분 중 하나입니다. 파이썬을 사용해서 어떻게 시각화하는지 알려주셔서 감사합니다!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (2, 8, '데이터 시각화는 복잡한 데이터를 이해하고 효과적으로 전달하는 데 큰 도움이 됩니다. 파이썬으로 시각화하는 방법을 배우는 것은 정말 유용해요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (2, 9, '파이썬을 이용한 데이터 시각화에 대한 튜토리얼은 언제나 환영입니다. 이 피드를 통해 새로운 시각화 기술을 배울 수 있어서 기쁩니다!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (3, 10, '자바스크립트의 최신 기능들을 항상 기대하고 있었어요. 어떤 새로운 기능이 있는지 알아보기가 정말 흥미로워요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (3, 11, 'ES6 이후로 자바스크립트가 많이 발전했는데, 이런 피드를 통해 최신 기능들을 배울 수 있어서 좋아요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (3, 12, '최신 자바스크립트 기능을 익히는 것은 프론트엔드 개발자로서 필수입니다. 이런 정보를 공유해주셔서 감사합니다!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (4, 1, 'CSS 그리드 시스템은 웹 개발에서 필수 도구 중 하나입니다. 이런 자세한 안내를 제공해주셔서 감사합니다!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (4, 2, 'CSS 그리드를 사용하는 방법을 배우는 것은 웹 개발자로서 중요한 스킬 중 하나에요. 이 피드를 통해 많은 도움을 받았습니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (4, 4, 'CSS 그리드 시스템에 대한 안내가 더 많이 필요한데, 이 피드는 정말 유용하네요. 앞으로도 이런 정보를 기대하고 있어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (5, 5, '머신러닝은 항상 흥미로운 주제인데, 파이썬을 사용한 프로젝트를 보여주셔서 감사합니다!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (5, 6, '머신러닝 프로젝트는 항상 도전적이지만, 파이썬을 사용하면 어떤 문제든 해결할 수 있어요. 이런 프로젝트를 공유해주셔서 고맙습니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (5, 7, '파이썬을 통해 머신러닝을 하려는데 도움이 필요했어요. 이 피드를 보고 많은 것을 배웠습니다. 더 많은 프로젝트를 기대하고 있어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (6, 8, '새로운 웹 개발 도구와 라이브러리를 소개해주셔서 감사합니다! 항상 새로운 기술을 익히는 것은 흥미로운 일이에요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (6, 9, '웹 개발에서는 끊임없는 변화가 있어서 최신 기술을 알고 있어야 합니다. 이런 소개 피드는 정말 유용합니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (6, 10, '새로운 웹 개발 도구와 라이브러리에 대한 정보를 찾고 있었는데, 이런 소개 피드를 보고 도움을 받았습니다. 감사합니다!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (7, 11, '협업을 위한 Git과 GitHub 사용 방법을 알려주셔서 고맙습니다! 코드 협업은 항상 복잡한데, 이런 정보가 도움이 많이 됩니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (7, 12, 'Git과 GitHub는 개발자들 간의 협업을 용이하게 만들어주는 중요한 도구입니다. 이런 피드를 통해 더 많이 배울 수 있어서 기뻐요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (7, 1, 'Git과 GitHub를 제대로 활용하는 방법을 찾고 있었는데, 이 피드를 보면서 많은 것을 배웠습니다. 더 많은 정보를 공유해주셨으면 좋겠어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (8, 2, 'AWS 클라우드 서비스에 대한 기초를 배우는 것은 중요한데, 이런 정보를 제공해주셔서 감사합니다!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (8, 3, '클라우드 서비스를 사용하면 더 효율적으로 개발할 수 있어요. AWS에 대한 기초를 잘 익히는 것이 중요합니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (8, 4, 'AWS 클라우드를 사용하는 방법을 배우려고 했는데, 이 피드를 보고 많은 것을 배웠습니다. 더 많은 정보를 기대하고 있어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (9, 5, 'Docker를 사용한 컨테이너화와 배포 전략에 대한 정보를 제공해주셔서 감사합니다! 이런 내용은 개발자에게 매우 유용해요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (9, 6, '컨테이너화와 배포 전략은 현대 소프트웨어 개발에서 핵심적인 역할을 합니다. Docker를 활용하는 방법을 배울 수 있어서 기쁩니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (9, 7, 'Docker와 컨테이너화에 대한 정보가 필요했는데, 이 피드를 통해 많은 것을 배웠습니다. 더 많은 내용을 공유해주셨으면 좋겠어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (10, 8, '개발자 커리어 관리에 대한 유용한 팁을 공유해주셔서 감사합니다! 자신의 커리어를 효과적으로 관리하는 것은 중요합니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (10, 9, '개발자로서 커리어를 관리하는 것은 항상 도전적입니다. 이런 팁을 통해 더 나은 방향으로 나아갈 수 있을 것 같아요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (10, 10, '개발자로서 성장하고자 하는 분들에게 좋은 조언이 될 것 같아요. 이런 내용을 더 많이 공유해주셨으면 좋겠어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (11, 11, 'Vue.js로 프론트엔드 개발을 시작하는 것은 좋은 선택입니다! 이 피드를 통해 더 많은 정보를 얻을 수 있어서 기뻐요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (11, 12, 'Vue.js는 학습 곡선이 다른 프레임워크에 비해 낮아 더 쉽게 시작할 수 있는데, 이 피드를 보면서 도움을 받았습니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (11, 1, '프론트엔드 개발에 관심이 있었는데, Vue.js로 시작하는 방법을 알려주셔서 감사합니다. 더 많은 학습 자료를 기대하고 있어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (12, 2, 'REST API 디자인에 관한 원칙과 예시를 공유해주셔서 감사합니다! 좋은 API 디자인은 개발 프로젝트의 핵심입니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (12, 3, 'REST API 디자인은 프로젝트의 성공과 밀접한 관련이 있습니다. 이런 정보를 공유해주셔서 고맙습니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (12, 4, 'REST API 디자인에 대한 가이드와 예시가 필요했는데, 이 피드를 통해 많은 것을 배웠습니다. 더 많은 정보를 공유해주시면 좋겠어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (13, 5, '프론트엔드와 백엔드 개발 모두 중요한 역할이지만, 어떤 경로를 선택할지 고민 중입니다. 이런 토론 피드는 유용하네요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (13, 6, '프론트엔드와 백엔드 개발 모두 자신만의 장점과 어려움이 있어서 선택이 어려운데, 이런 주제에 대한 토론은 항상 도움이 됩니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (13, 7, '프론트엔드와 백엔드 개발 중 어느 쪽으로 나아갈지 고민 중이었는데, 이 피드를 보면서 어떤 경로를 선택해야 할지 더 명확해졌습니다. 더 많은 정보를 공유해주셨으면 좋겠어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (14, 8, '데이터베이스 최적화 전략에 대한 정보를 공유해주셔서 감사합니다! 데이터베이스 성능 최적화는 항상 중요한 주제 중 하나에요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (14, 9, '데이터베이스 최적화는 개발 프로젝트의 성능과 확장성에 큰 영향을 미칩니다. 이런 전략을 배우는 것은 중요합니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (14, 10, '데이터베이스 최적화에 대한 정보가 필요했는데, 이 피드를 보면서 많은 것을 배웠습니다. 더 많은 전략과 팁을 기대하고 있어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (15, 11, 'AWS Lambda와 서버리스 아키텍처에 대한 소개를 읽어봤는데, 정말 흥미로웠습니다! 서버리스 개발은 미래를 대비하는 좋은 방법이에요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (15, 12, '서버리스 아키텍처는 미래의 개발 방향 중 하나로 보이는데, AWS Lambda에 대한 정보를 얻을 수 있어서 기뻐요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (15, 1, 'AWS Lambda와 서버리스 아키텍처에 대한 정보가 필요했는데, 이 피드를 보면서 많은 것을 배웠습니다. 더 많은 내용을 공유해주셨으면 좋겠어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (16, 2, '프로그래밍 언어 선택은 중요한 결정 중 하나에요. 이런 가이드를 통해 언어를 선택하는 데 도움을 받을 수 있어서 고마워요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (16, 3, '다양한 프로그래밍 언어가 있는데, 어떤 언어를 선택해야 할지 고민이었어요. 이런 정보를 통해 더 나은 결정을 내릴 수 있을 것 같아요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (16, 5, '프로그래밍 언어 선택은 개발 프로젝트의 성패에 큰 영향을 미치니까 신중하게 고려해야 해요. 이런 가이드를 보면서 도움을 받았습니다. 더 많은 정보를 기대하고 있어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (17, 6, '커뮤니티 참여를 통한 개발자 네트워킹은 정말 중요하죠! 다른 개발자와 소통하고 배울 수 있는 기회가 많아요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (17, 7, '커뮤니티 참여는 개발자로서 성장하는 데 큰 도움이 됩니다. 이런 주제에 대한 정보를 얻을 수 있어서 기뻐요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (17, 8, '커뮤니티에서 다른 개발자들과 연결되는 것은 네트워킹을 향상시키는 좋은 방법 중 하나에요. 이런 피드를 통해 더 많은 영감을 받을 수 있을 것 같아요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (18, 9, '웹 보안은 모든 개발자에게 필수적인 주제 중 하나에요. 이런 정보를 공유해주셔서 감사합니다!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (18, 10, '웹 보안 취약점은 많은 위험을 가져올 수 있습니다. 이런 전략을 배우는 것은 중요합니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (18, 11, '웹 보안에 대한 정보가 필요했는데, 이 피드를 보면서 많은 것을 배웠습니다. 더 많은 보안 전략과 팁을 기대하고 있어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (19, 12, '애자일 소프트웨어 개발 방법론은 현대 개발 프로세스의 필수 요소 중 하나입니다. 이런 정보를 제공해주셔서 감사합니다!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (19, 1, '애자일 방법론은 소프트웨어 개발을 더 효율적으로 만드는데 도움이 됩니다. 이런 주제에 대한 정보를 얻을 수 있어서 기뻐요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (19, 3, '애자일 소프트웨어 개발 방법론을 배우려고 했는데, 이 피드를 보면서 많은 것을 배웠습니다. 더 많은 내용을 기대하고 있어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (20, 4, '커리어 전환은 언제나 도전적이지만, 데브옵스 엔지니어로의 전환에 관한 정보를 제공해주셔서 감사합니다!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (20, 5, '데브옵스 엔지니어로의 커리어 전환은 현대 소프트웨어 개발에서 중요한 주제 중 하나입니다. 이런 정보를 얻을 수 있어서 기뻐요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (20, 6, '개발자에서 데브옵스 엔지니어로 전환하려는데, 이 피드를 보면서 어떤 단계를 밟아야 할지 알게 되었습니다. 더 많은 정보를 공유해주셨으면 좋겠어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (21, 7, 'GraphQL을 사용한 API 개발에 대한 팁을 공유해주셔서 감사합니다! GraphQL은 혁신적인 기술 중 하나에요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (21, 8, 'GraphQL을 사용한 API 개발은 데이터 요청과 응답을 효율적으로 만드는데 도움이 됩니다. 이런 정보를 얻을 수 있어서 기뻐요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (21, 9, 'GraphQL을 처음 사용해보려고 했는데, 이 피드를 보면서 많은 것을 배웠습니다. 더 많은 개발 팁을 공유해주셨으면 좋겠어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (22, 10, 'CI/CD 파이프라인 구축은 개발 프로젝트의 자동화와 안정성을 향상시키는데 중요한 요소 중 하나에요. 이런 정보를 제공해주셔서 감사합니다!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (22, 11, 'CI/CD 파이프라인은 현대 소프트웨어 개발에서 필수적인 부분입니다. 이런 내용을 배울 수 있어서 기뻐요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (22, 12, 'CI/CD 파이프라인을 구축하는 방법에 대한 정보가 필요했는데, 이 피드를 보면서 많은 것을 배웠습니다. 더 많은 도움을 기대하고 있어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (23, 2, '컴퓨터 과학 기초는 모든 개발자에게 필수적인 부분이에요. 이런 주제를 다루는 것은 좋은 아이디어에요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (23, 3, '컴퓨터 과학 기초를 다시 공부하고 싶었는데, 이 피드를 보면서 시작할 수 있을 것 같아요. 감사합니다!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (23, 4, '컴퓨터 과학 기초에 대한 정보가 필요했는데, 이 피드를 통해 많은 것을 배웠습니다. 더 많은 내용을 기대하고 있어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (24, 5, '웹 개발에서 성능 최적화는 매우 중요한 주제 중 하나에요. 이런 정보를 공유해주셔서 감사합니다!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (24, 6, '웹 개발에서 성능 최적화는 사용자 경험을 향상시키는데 큰 역할을 합니다. 이런 내용을 배울 수 있어서 기뻐요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (24, 7, '웹 개발 성능 최적화에 대한 정보가 필요했는데, 이 피드를 보면서 많은 것을 배웠습니다. 더 많은 최적화 전략과 팁을 기대하고 있어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (25, 8, '오픈 소스 개발에 기여하는 방법에 대한 정보를 공유해주셔서 감사합니다! 오픈 소스 커뮤니티에 기여하면 개발자로서 더 많은 성장 기회가 있어요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (25, 9, '오픈 소스 프로젝트에 기여하는 것은 개발자로서 의미 있는 일 중 하나에요. 이런 주제에 대한 정보를 얻을 수 있어서 기뻐요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (25, 10, '오픈 소스 개발에 처음으로 기여하려는데, 이 피드를 보면서 어떻게 시작해야 할지 알게 되었습니다. 더 많은 기여 방법을 알려주셨으면 좋겠어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (26, 11, 'React, Angular, Vue를 비교하는 토론은 항상 흥미로운 주제에요. 어떤 프레임워크가 최적인지에 대한 정보는 개발자에게 큰 가치가 있어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (26, 12, 'JavaScript 프레임워크를 선택할 때 항상 고민이 되는데, 이런 비교 피드를 보면서 더 나은 결정을 내릴 수 있을 것 같아요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (26, 1, 'React vs. Angular vs. Vue 비교에 대한 정보가 필요했는데, 이 피드를 보면서 각각의 장단점을 이해할 수 있었습니다. 더 많은 비교 자료를 공유해주셨으면 좋겠어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (27, 2, '데이터 사이언스와 머신러닝 프로젝트에 대한 정보를 공유해주셔서 감사합니다! 이런 주제는 데이터 분석과 예측에 관심 있는 사람에게 유용할 것 같아요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (27, 3, '데이터 사이언스와 머신러닝 프로젝트는 실무 경험을 쌓는 데 매우 중요합니다. 이런 내용을 배울 수 있어서 기쁩니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (27, 5, '머신러닝 실전 프로젝트에 대한 정보가 필요했는데, 이 피드를 보면서 많은 것을 배웠습니다. 더 많은 프로젝트 예시와 팁을 기대하고 있어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (28, 6, '코딩 인터뷰를 위한 팁과 자료 구조 문제 해결 전략은 개발자로서 중요한 능력 중 하나에요. 이런 정보를 공유해주셔서 감사합니다!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (28, 7, '코딩 인터뷰는 많은 개발자들에게 스트레스를 주는 주제 중 하나입니다. 이런 주제에 대한 정보를 얻을 수 있어서 기뻐요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (28, 8, '코딩 인터뷰에서 자료 구조 문제를 해결하는 방법이 궁금했는데, 이 피드를 보면서 유용한 팁을 배울 수 있었습니다. 더 많은 문제 해결 전략을 공유해주셨으면 좋겠어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (29, 9, '클라우드 보안에 대한 Best Practices를 공유해주셔서 감사합니다! 클라우드 보안은 모든 기업에게 중요한 주제 중 하나에요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (29, 10, '클라우드 보안은 신경 써야 할 중요한 주제 중 하나입니다. 이런 정보를 얻을 수 있어서 기뻐요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (29, 11, '클라우드 보안 Best Practices에 대한 정보가 필요했는데, 이 피드를 보면서 어떻게 보안을 강화할 수 있는지에 대한 아이디어를 얻을 수 있었습니다. 더 많은 팁을 공유해주셨으면 좋겠어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (30, 12, '개발자 커뮤니티에서 활동하고 혜택을 얻는 것은 개발자 커리어에 도움이 되는 좋은 방법 중 하나에요. 이런 정보를 제공해주셔서 감사합니다!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (30, 1, '개발자 커뮤니티에서의 활동은 지식 공유와 네트워킹을 향상시키는데 도움이 됩니다. 이런 주제에 대한 정보를 얻을 수 있어서 기쁘요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (30, 3, '개발자 커뮤니티에서 활동하기에 대한 정보가 필요했는데, 이 피드를 보면서 어떻게 참여하고 혜택을 얻을 수 있는지에 대한 가이드를 얻을 수 있었습니다. 더 많은 활동 방법과 혜택을 공유해주셨으면 좋겠어요!', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (31, 5, 'Redux와 Context API는 각각 상태 관리에 유용한 도구입니다. Redux는 큰 규모의 앱 또는 복잡한 상태 관리에 적합하며, Context API는 작은 규모의 앱이나 단순한 상태 관리에 좋습니다. 프로젝트의 크기와 요구 사항에 따라 선택하세요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (31, 6, 'Redux 대신 Context API를 선택할 때, 상태 관리를 더 간단하게 구현할 수 있습니다. 그러나 Redux는 미들웨어와 같은 고급 기능을 제공하므로 복잡한 앱에서 더욱 강력할 수 있습니다. 프로젝트의 본질과 목표에 따라 선택하세요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (31, 7, 'Redux와 Context API는 둘 다 유효한 상태 관리 도구입니다. Redux는 예측 가능하고 확장 가능한 앱을 구축하기 위해 디자인되었으며, Context API는 간단한 앱에서 더 쉽게 시작할 수 있습니다. 프로젝트의 요구 사항을 고려하여 결정하세요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (32, 8, 'Python과 JavaScript는 웹 개발에 모두 사용될 수 있지만, 목적과 선호도에 따라 다를 수 있습니다. Python은 데이터 과학 및 백엔드 개발에 더 적합하고, JavaScript는 프런트엔드 및 웹 애플리케이션 개발에 특화되어 있습니다. 프로젝트의 요구 사항과 개발자의 스킬셋을 고려하여 선택하세요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (32, 9, 'Python과 JavaScript는 웹 개발에 각기 다른 강점을 가지고 있습니다. Python은 간결하고 읽기 쉬운 코드를 작성하는 데 도움이 되며, JavaScript는 프런트엔드 상호작용과 빠른 웹 애플리케이션 개발에 강점을 가집니다. 프로젝트의 목적과 기술적 요구 사항을 고려하여 선택하세요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (32, 10, 'Python과 JavaScript는 모두 웹 개발에 사용될 수 있는 다재다능한 언어입니다. 개발자의 선호도, 프로젝트의 본질, 팀의 스킬셋을 고려하여 선택해야 합니다. 때로는 두 언어를 혼합하여 사용하기도 합니다. 중요한 것은 프로젝트의 목표와 요구 사항을 충족하는 언어를 선택하는 것입니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (33, 11, 'Git 충돌 해결은 중요한 스킬 중 하나에요. 가장 중요한 것은 충돌이 발생하면 두 버전을 비교하고 수동으로 수정하는 것입니다. 그리고 충돌이 발생하지 않도록 주기적으로 코드를 푸시하는 것도 중요해요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (33, 12, 'Git 충돌 해결을 위한 좋은 방법은 충돌을 방지하는 것입니다. 다른 팀원과 코드를 공유하기 전에 자주 푸시하고, 충돌이 발생하지 않도록 주의해야 합니다. 그러나 충돌이 발생하면 주석과 코드 라인을 이해하고, 프로젝트의 목표를 고려하여 수정하세요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (33, 2, 'Git 충돌은 피할 수 없는 경우가 많습니다. 최상의 방법은 충돌이 발생하면 빠르게 대응하고, 코드를 자세히 검토하여 올바르게 수정하는 것입니다. 다른 팀원과 협력하여 충돌을 해결하고, 팀의 Git 흐름을 잘 이해하는 것이 중요합니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (34, 3, '프론트엔드 개발자로 취업하려면 HTML, CSS, JavaScript는 필수입니다. 이후에는 React, Angular, 또는 Vue와 같은 프레임워크를 익히는 것이 좋습니다. 또한 Git 및 웹 개발 도구와 협업 능력도 중요합니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (34, 4, '프론트엔드 개발자가 되기 위해서는 웹 기초인 HTML, CSS, JavaScript를 먼저 마스터해야 합니다. 그리고 React, Angular, Vue와 같은 프레임워크나 라이브러리를 익혀야 하며, 프로젝트 관리 및 협업 능력도 키워야 합니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (34, 5, '프론트엔드 개발자로 취업하려면 기본적으로 HTML, CSS, JavaScript를 이해하고 있어야 합니다. 그리고 React 또는 Vue와 같은 프론트엔드 프레임워크를 배우는 것이 좋습니다. 또한 웹 개발 도구와 협업 도구도 숙지하고 프로젝트 경험을 쌓아보세요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (35, 6, '안드로이드와 iOS 모두 중요한 시장을 보유하고 있으며, 플랫폼 선택은 여러 요소에 의해 좌우됩니다. 개발자의 선호도, 타겟 사용자, 비즈니스 목표에 따라 선택하세요. 두 플랫폼 모두 기회가 많습니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (35, 7, '안드로이드와 iOS 개발 모두 장점과 한계가 있습니다. 안드로이드는 다양한 디바이스에 대응하고 대중적이지만, iOS는 보안 및 사용자 경험 측면에서 강점이 있습니다. 플랫폼 선택은 프로젝트의 목표와 대상을 고려하여 결정해야 합니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (35, 8, '안드로이드와 iOS 모두 시장 점유율이 높고 기회가 많습니다. 하지만 개발 시간과 비용, 사용자 피드백 등을 고려하여 플랫폼을 선택해야 합니다. 또한 앱을 양 플랫폼에 출시하는 것도 고려해볼 가치가 있습니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (36, 9, 'RESTful API와 GraphQL은 각각 장단점이 있습니다. RESTful은 간단하고, 캐싱 및 보안에 강점을 가지며, 기존 API와 호환성이 좋습니다. GraphQL은 유연하고 요청에 따라 데이터를 조절할 수 있어 특별한 경우에 적합합니다. 프로젝트의 목표와 요구 사항에 따라 선택하세요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (36, 10, 'API 선택은 프로젝트의 본질과 요구 사항에 따라 다릅니다. RESTful은 단순하고 예측 가능하며, GraphQL은 유연하고 효율적입니다. 팀의 경험과 프로젝트의 복잡성을 고려하여 결정하세요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (36, 11, 'RESTful API와 GraphQL은 각각 장점과 한계가 있습니다. RESTful은 기본 웹 표준을 따르며 간단한 API에 적합합니다. GraphQL은 데이터 요구 사항이 다양한 경우에 적합하며, 클라이언트 측에서 데이터를 원하는대로 검색할 수 있습니다. 프로젝트의 복잡성과 목표를 고려하여 선택하세요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (37, 12, 'Docker와 Kubernetes는 컨테이너 관리와 오케스트레이션에 중요한 역할을 합니다. Docker는 컨테이너화 기술로 애플리케이션을 쉽게 배포하고 실행할 수 있게 해주며, Kubernetes는 여러 컨테이너를 자동으로 관리해주는 도구입니다. 각각의 핵심 개념과 기능을 공부하면 컨테이너 오케스트레이션을 이해하는 데 도움이 됩니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (37, 1, 'Docker와 Kubernetes는 현대적인 애플리케이션 배포와 관리를 위한 핵심 기술입니다. Docker는 애플리케이션과 종속성을 컨테이너로 패키징하여 환경을 격리시키는 데 사용되며, Kubernetes는 이러한 컨테이너를 효율적으로 스케일링하고 관리합니다. 두 기술을 숙지하면 컨테이너 오케스트레이션에 대한 이해가 높아질 것입니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (37, 2, '컨테이너 오케스트레이션은 현대적인 애플리케이션 배포에 필수적입니다. Docker는 애플리케이션을 환경에서 격리시키는 데 사용되며, Kubernetes는 이러한 컨테이너를 효율적으로 관리합니다. 기본 개념과 용어를 학습하고, 실습을 통해 실제로 사용해보면 이해가 빠를 것입니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (38, 3, 'TDD의 가장 큰 장점은 안정적인 코드와 빠른 버그 탐지입니다. 먼저 테스트 케이스를 작성하고, 이 테스트를 통과할 코드를 개발하는 방식으로 시작합니다. 작은 기능부터 시작하여 전체 애플리케이션을 개발하는 데 도움이 됩니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (38, 4, 'TDD를 시작하려면 먼저 프로젝트의 목표와 요구 사항을 이해하세요. 그런 다음 첫 번째 테스트 케이스를 작성하고, 이를 통과할 코드를 작성하세요. 그리고 이 과정을 반복합니다. 이렇게 하면 안정적이고 유지 보수가 쉬운 코드를 개발할 수 있습니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (38, 5, 'TDD를 시작하는 데 있어서 먼저 테스트 케이스를 작성하는 것이 중요합니다. 이 테스트 케이스는 기능의 예상 동작을 정의하고, 이를 통과하는 코드를 작성하게끔 유도합니다. 점진적으로 기능을 추가하고 리팩토링하면서 코드 품질을 향상시킬 수 있습니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (39, 6, '웹 애플리케이션 보안을 강화하기 위해 먼저 적절한 입력 유효성 검사를 수행하세요. 사용자 입력을 신뢰하지 마시고, SQL 인젝션, 크로스 사이트 스크립팅(XSS), 크로스 사이트 요청 위조(CSRF) 등과 같은 보안 취약점을 예방하세요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (39, 7, '웹 애플리케이션을 보호하기 위해 보안 헤더를 올바르게 설정하세요. Content Security Policy (CSP), X-Content-Type-Options, X-Frame-Options, 및 X-XSS-Protection과 같은 헤더를 사용하여 공격을 방지하세요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (39, 8, '보안 패치를 항상 최신으로 유지하고, 보안 업데이트를 적용하세요. 또한 보안 테스트와 코드 리뷰를 통해 애플리케이션의 취약점을 식별하고, 보안 관행을 준수하는 개발자 교육을 실시하세요. 사용자 권한 관리와 로깅을 통해 비정상적인 활동을 탐지하고 대응하세요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (40, 9, '데브옵스 엔지니어로의 커리어 전환은 계획과 노력이 필요한 과정입니다. 먼저 현재 기술 스택과 데브옵스 관련 도구 및 프로세스에 대한 학습을 시작하세요. CI/CD, 자동화, 컨테이너화와 같은 주요 개념을 익히세요.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (40, 10, '개발자에서 데브옵스 엔지니어로의 전환은 경험과 실전 프로젝트가 중요합니다. 팀 프로젝트에서 CI/CD 파이프라인을 설정하거나 인프라 자동화 작업을 수행하면서 실무 경험을 쌓아보세요. 또한 커뮤니티 활동과 오픈 소스 기여도 도움이 됩니다.', 'N');
INSERT INTO parent_comments (feed_id, user_id, content, delete_yn) VALUES (40, 11, '데브옵스 엔지니어로의 커리어 전환은 지속적인 학습과 인지력을 필요로 합니다. 새로운 기술과 트렌드를 습득하고, 문제 해결 능력을 키워나가세요. 데브옵스 엔지니어로서의 역할과 책임을 이해하고, 현재 업계 동향을 파악하세요.', 'N');

INSERT INTO feed_questions (feed_id, user_id, content, deposit, status, question_due_date) VALUES (1, 4, 'React에서 Redux 대신 Context API를 사용하는 것에 대한 장단점은 무엇일까요?', 3000, 'RESOLVING', '2023-09-30 12:00:00');
INSERT INTO feed_questions (feed_id, user_id, content, deposit, status, question_due_date) VALUES (5, 2, 'Python과 JavaScript 중 어떤 언어가 웹 개발에 더 적합한가요?', 2000, 'RESOLVING', '2023-10-15 14:30:00');
INSERT INTO feed_questions (feed_id, user_id, content, deposit, status, question_due_date) VALUES (14, 1, '프론트엔드 개발자로 취업하기 위해 어떤 기술 스택을 익혀야 할까요?', 2500, 'RESOLVING', '2023-10-10 10:00:00');
INSERT INTO feed_questions (feed_id, user_id, content, deposit, status, question_due_date) VALUES (17, 3, '안드로이드 vs. iOS 개발 중 어느 쪽이 미래에 더 유망한가요?', 3500, 'RESOLVING', '2023-10-05 16:45:00');
INSERT INTO feed_questions (feed_id, user_id, content, deposit, status, question_due_date) VALUES (19, 5, 'RESTful API와 GraphQL 중 어떤 것을 선택해야 할까요?', 3000, 'RESOLVING', '2023-09-25 11:20:00');
INSERT INTO feed_questions (feed_id, user_id, content, deposit, status, question_due_date) VALUES (23, 2, 'Docker와 Kubernetes에 대한 기본 개념을 알려주세요.', 2000, 'RESOLVING', '2023-10-01 09:15:00');
INSERT INTO feed_questions (feed_id, user_id, content, deposit, status, question_due_date) VALUES (26, 1, 'TDD의 장점은 무엇이며, 어떻게 시작해야 할까요?', 2500, 'RESOLVING', '2023-10-20 13:10:00');
INSERT INTO feed_questions (feed_id, user_id, content, deposit, status, question_due_date) VALUES (29, 2, '웹 애플리케이션 보안을 위한 팁과 자료 추천 부탁드립니다.', 3000, 'RESOLVING', '2023-09-28 15:30:00');
INSERT INTO feed_questions (feed_id, user_id, content, deposit, status, question_due_date) VALUES (31, 3, '개발자에서 데브옵스 엔지니어로의 커리어 전환 조언을 부탁드립니다.', 3500, 'RESOLVING', '2023-10-03 17:00:00');
INSERT INTO feed_questions (feed_id, user_id, content, deposit, status, question_due_date) VALUES (2, 3, 'Redux vs. Context API 선택 시의 장단점은 무엇인가요?', 2500, 'RESOLVED', '2023-09-25 14:00:00');
INSERT INTO feed_questions (feed_id, user_id, content, deposit, status, question_due_date) VALUES (7, 5, 'Python과 JavaScript의 웹 개발 용도 비교', 2000, 'RESOLVED', '2023-10-10 15:45:00');
INSERT INTO feed_questions (feed_id, user_id, content, deposit, status, question_due_date) VALUES (15, 3, '프론트엔드 개발자로서 필수적인 기술 스택', 3000, 'RESOLVED', '2023-10-05 16:30:00');
INSERT INTO feed_questions (feed_id, user_id, content, deposit, status, question_due_date) VALUES (18, 4, '안드로이드와 iOS 개발의 장단점 비교', 3500, 'RESOLVED', '2023-09-30 18:20:00');
INSERT INTO feed_questions (feed_id, user_id, content, deposit, status, question_due_date) VALUES (21, 5, 'RESTful API vs. GraphQL 선택 가이드', 3000, 'RESOLVED', '2023-10-15 12:00:00');
INSERT INTO feed_questions (feed_id, user_id, content, deposit, status, question_due_date) VALUES (25, 2, 'Docker와 Kubernetes 시작하기', 2000, 'RESOLVED', '2023-10-20 10:30:00');
INSERT INTO feed_questions (feed_id, user_id, content, deposit, status, question_due_date) VALUES (28, 3, 'TDD를 효과적으로 시작하는 방법', 2500, 'RESOLVED', '2023-10-03 14:15:00');
INSERT INTO feed_questions (feed_id, user_id, content, deposit, status, question_due_date) VALUES (32, 1, '웹 애플리케이션 보안 강화 방법', 3000, 'RESOLVED', '2023-09-28 11:45:00');
INSERT INTO feed_questions (feed_id, user_id, content, deposit, status, question_due_date) VALUES (33, 4, '데브옵스 엔지니어로의 커리어 전환 팁', 3500, 'RESOLVED', '2023-09-25 16:00:00');